# Generated by Django 2.0.2 on 2018-05-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180429_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='some status', max_length=128),
        ),
    ]
