version: '3'

services:

  store_db:
    container_name: store_db
    image: postgres


  warehouse_db:
    container_name: warehouse_db
    image: postgres

  crestopher:
    build: .
    container_name: crestopher
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - store_db
      - warehouse_db