version: '3'

services:

  store_db:
    container_name: store_db
    image: postgres
    ports:
      - "54321:5432"


  warehouse_db:
    container_name: warehouse_db
    image: postgres
    ports:
      - "54322:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"      

  crestopher:
    build: .
    container_name: crestopher
    command: [sh, -c, "python3 manage.py runserver 0.0.0.0:8000 & celery -A crestopher worker -l info"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - store_db
      - warehouse_db
      - redis