version: '3'

services:

  store_db:
    container_name: store_db
    image: postgres
    ports:
      - "54321:5432"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data


  warehouse_db:
    container_name: warehouse_db
    image: postgres
    ports:
      - "54322:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  crestopher:
    build: .
    container_name: crestopher
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - store_db
      - warehouse_db